"""create messages table

Revision ID: 8fc18f8204ac
Revises: b22e968339f8
Create Date: 2025-09-26 22:53:41.297580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc18f8204ac'
down_revision = 'b22e968339f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
