"""create messages table

Revision ID: 901853bdd873
Revises: 8fc18f8204ac
Create Date: 2025-09-26 22:55:13.926330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901853bdd873'
down_revision = '8fc18f8204ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
